### ISSUE TITLE
Product fork is not there

### ISSUE THREAD

**Issue by hamzawey** [letimome/GitLine#13]
Hi, 

I installed the gitline extension on firefox 37.0. However, product fork is not showing. 
I followed the instructions as mentioned and also renamed the folder to be scxmlGitDelta@onekin.org as mentioned in the other open issue. 
here is a screen shot of the add-ons manager:
![manage-add-ons](https://cloud.githubusercontent.com/assets/6915568/14472216/5acd1328-00af-11e6-9306-ca8ff1f14288.png)

Not sure what else is missing. 
Thanks, 
Mostafa

**Comment by letimome** [comment]
Hi Mostafa!

Thanks for reporting. This is a common issue GitLine faces due to Github changing the webpage rendering...  

I fixed the error. Tell me if now you can see "product Fork" button. For me it works
![captura de pantalla 2016-04-13 a las 17 45 02](https://cloud.githubusercontent.com/assets/5872026/14499886/396327e4-01a0-11e6-8c14-08b4625be537.png)
Don't forget adding your "access token" to githubdeltas.js, as otherwise "product fork" button wouldn't appear.



By the way, make sure you have v37.0 installed. My Add-on page looks a bit different than yours,

![captura de pantalla 2016-04-13 a las 17 45 51](https://cloud.githubusercontent.com/assets/5872026/14499984/862add38-01a0-11e6-9527-c9c7a1cba6ae.png)

Cheers,
Leticia

**Comment by hamzawey** [comment]
Thanks Leticia, 
Now it is working for me.

**Comment by lemome88** [comment]
Great!

**Comment by letimome** [comment]
Great!
